version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: resume-analyzer-postgres
    environment:
      POSTGRES_DB: resume_analyzer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - resume-network

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: resume-analyzer-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - resume-network

  # n8n Automation Platform
  n8n:
    image: n8nio/n8n:latest
    container_name: resume-analyzer-n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_LOG_LEVEL=info
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_BINARY_DATA_TTL=3600
      - N8N_BINARY_DATA_MAX_SIZE=16777216
      - N8N_EDITOR_BASE_URL=http://localhost:5678/
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
      - N8N_ENCRYPTION_KEY=your-encryption-key-change-in-production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/.n8n/workflows
      - ./backend/uploads:/home/node/.n8n/uploads
    ports:
      - "5678:5678"
    depends_on:
      - postgres
    networks:
      - resume-network
    restart: unless-stopped

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resume-analyzer-backend
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/resume-upload
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - n8n
    networks:
      - resume-network
    restart: unless-stopped

volumes:
  postgres_data:
  n8n_data:

networks:
  resume-network:
    driver: bridge
